modLoader="javafml"
loaderVersion="*"
license="All rights reserved"
issueTrackerURL="https://github.com/ricksouth/serilum-mc-mods/labels/Mod:%20Hidden%20Recipe%20Book"
logoFile="icon.png"

[[mods]]
modId="hiddenrecipebook"
version="4.3"
displayName="Hidden Recipe Book"
displayURL="https://curseforge.com/minecraft/mc-mods/hidden-recipe-book"
authors="Rick South"
description='''Hides the recipe book on crafting and furnace GUIs, toggleable via a hotkey.
'''
credits='''Thank you very much to my Membership sponsors for supporting the development of this mod:  

Adam E, Alister, aternosorg, Cherriesaurus, FireStriker, Greg Johnson, Kreezxil, Michael W. S., Mir3JonCZ, Rebecca Hb., Shana Gitnick, silver Bowsman, Tyler Behl   

If you would like to contribute too, check out https://ricksouth.com/donate. Appreciate it! <3   
'''

[[dependencies.hiddenrecipebook]]
    modId="collective"
    mandatory=true
    versionRange="[7.5,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.hiddenrecipebook]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.2]"
    ordering="NONE"
    side="BOTH"

[[mixins]]
    config = "hiddenrecipebook_neoforge.mixins.json"