modLoader="javafml"
loaderVersion="*"
license="All Rights Reserved"
issueTrackerURL="https://github.com/Serilum/.issue-tracker/labels/Mod:%20Hidden%20Recipe%20Book"
logoFile="icon.png"

[[mods]]
modId="hiddenrecipebook"
version="5.3"
displayName="Hidden Recipe Book"
displayURL="https://serilum.com/mod/hidden-recipe-book"
authors="Serilum"
description='''Hides the recipe book on crafting and furnace GUIs, toggleable via a hotkey.
'''
credits='''Thank you very much to my Membership sponsors for supporting the development of this mod:  

Andrean Olgo, AnyankaT, aternosorg, Cherriesaurus, Linda Jansen, MWS, Tyler Behl   

If you would like to contribute too, check out https://serilum.com/donate Appreciate it! <3   
'''

[[dependencies.hiddenrecipebook]]
    modId="collective"
    mandatory=true
    versionRange="[8.40,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.hiddenrecipebook]]
    modId="minecraft"
    mandatory=true
    versionRange="[26.2]"
    ordering="NONE"
    side="BOTH"
